name = "glyph-light-default.toml"

[appearance]
bg = "#fefefe"
fg = "#222222"

[gutter]
bg = "#fefefe"
fg = "#aaaaaa"

[statusline]
inner = { fg = "#fefefe", bg = "#a869db" }

[tokens]
function = { fg = "#6B8E23" }
"function.method" = { fg = "#008B8B" }
"function.macro" = { fg = "#FF8C00" }
"constant.builtin" = { fg = "#4682B4" }
constant = { fg = "#B8860B" }
type = { fg = "#6495ED" }
"type.builtin" = { fg = "#20B2AA" }
constructor = { fg = "#778899" }
property = { fg = "#2E8B57" }
"variable.parameter" = { fg = "#6A5ACD" }
"variable.builtin" = { fg = "#9932CC" }
label = { fg = "#8FBC8F" }
comment = { fg = "#B0C4DE" }
"punctuation.bracket" = { fg = "#696969" }
"punctuation.delimiter" = { fg = "#696969" }
keyword = { fg = "#8A2BE2" }
string = { fg = "#D2691E" }
escape = { fg = "#B22222" }
operator = { fg = "#A52A2A" }
attribute = { fg = "#5F9EA0" }

